### PR TITLE
check it,please

### PR DESCRIPTION
**Pull request by huangpengtao**
Renamed git_script.sh  to git_init.sh

### CODE REVIEW

**Comment by pyKun** [comment]
why pull three commits here for one thing?

**Comment by huangpengtao** [comment]
first, I renamed file me git_script.sh  to git_init.sh and click button Commit directly to the master branch.
then I am sure that I can finish the work. so I resume the file name and do it again. 
sorry for do this.

**Comment by pyKun** [comment]
@huangpengtao why resume and do it again? The two more commits are meaningless.

**Comment by huangpengtao** [comment]
I resume the file name for I can change the file name to git_init.sh of your need and click button Create a new branch for this commit and start a pull request to push to you.

**Comment by pyKun** [comment]
@huangpengtao you could upload only commit in this pull request

**Pull request closed without merging**
